### ISSUE TITLE
Can this be used to get files from c:\Quarantine?

### ISSUE THREAD

**Issue by ageev** [bmarandel/Collect-Files-Via-McAfee-ePO#1]
Hi!

Files in Quarantine folder have random names -> not possible to use the tool.
Can you please modify it so I can use it to copy the whole McAfee quarantine folder?

Regards, Artyom

**Comment by bmarandel** [comment]
Hi Artyom,

To collect files from the quarantine you can use the main package "Prepare file for collect" and pass the path "C:\Quarantine\quarantine\\*.zip" as the command line parameter. Because it may be difficult to rapidly identify the archive that store the quarantined file you are looking for, I crafted a dedicated package "Prepare Quarantine files for collect". This package is also building a QuarantineIndex.txt based on the local Quarantine.db file and will describe the content of all quarantine archives.

Hope that helps.
Ben.
